### ISSUE TITLE
Add sd_parsers to reqs

### ISSUE THREAD

**Issue by AveryVeilfaire** [deepratna-awale/AutoExpress#11]
I suggest adding sd_parsers to the env requirements. (I install SD via ST-Launcher, so might explain why I don't have it)

**Comment by deepratna-awale** [comment]
Commit https://github.com/deepratna-awale/AutoExpress/commit/a50c342765ab1c3534674a9c0c0b496bdac35a11 adds sd-parsers. Thanks for reporting it was missing.
