### ISSUE TITLE
python requirement pivy-deps

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [deepratna-awale/AutoExpress#8]
The requirement for `pivy-deps` (req'd for Flask, so maybe this is an upstream issue?) is only available (from pypi) for Windows. How much effort would it be to change things so that we linux people can make use of AutoExpress?

**Comment by deepratnaawale** [comment]
Hi, my requirements file does not explicitly require that, maybe try installing Flask using pip, and then post the error log here?
I don't specifically remember where it is used. 

PS: I'm working on a new release that will not be using Flask, so it probably might solve this issue.
